export const COPY = {
  arrival: {
    heading: 'welcome. you’re about to play for what matters.',
    subheading: 'enter your name to join the session.',
    nameLabel: 'your name',
    joinButton: 'join',
    waitingForFacilitator: 'we’re waiting for the facilitator to start. stretch a little.',
    codeLabel: 'session code',
  },
  timeline: {
    status: (index: number, total: number, name: string) =>
      `act ${index} of ${total} · ${name}`,
    next: (name: string) => `next: ${name}`,
    lastAct: 'final act',
    entering: (name: string) => `entering: ${name}`,
  },
  grouping: {
    heading: 'pick the strategy archetype that feels least like you.',
    caption:
      'we’re stretching you on purpose. pick the archetype you’d normally avoid — the auction is more honest when you can’t play safe.',
    options: [
      { key: 'builder', label: 'the builder — ship, measure, ship again.' },
      { key: 'diplomat', label: 'the diplomat — align everyone before a single move.' },
      { key: 'rebel', label: 'the rebel — burn the playbook and see what catches.' },
      { key: 'steward', label: 'the steward — protect what’s fragile, invest in what lasts.' },
    ] as const,
    confirm: 'team me up',
    assigned: (colour: string, others: number) =>
      `you’re with team ${colour}. ${others} ${others === 1 ? 'other is' : 'others are'} finding their seats.`,
  },
  scene: {
    ready: 'i’ve read it. ready.',
    sectorLabel: 'sector',
    budgetLabel: 'your budget',
  },
  company: {
    heading: 'meet your company.',
    intro: (credos: number) =>
      `you have ${credos} credos to spend. two values are already yours. here’s who you’re bidding against.`,
    renameLabel: 'company name',
    renameEdit: 'rename',
    renameSave: 'save',
    renameCancel: 'cancel',
    seedHeading: 'you start with',
    seedHint: 'these are yours. no bid needed.',
    credosLabel: 'credos to invest',
    rivalsHeading: 'your rivals',
    noRivals: 'no other teams this round.',
    ready: 'we’re ready.',
    waiting: 'waiting for other teams to ready up.',
  },
  strategy: {
    prompt: 'drag each value into a zone. your team must agree before the auction.',
    zones: {
      must: 'must have',
      nice: 'would be nice',
      wont: 'won’t fight for',
    },
    deckLabel: 'the deck',
    budgetHint: 'set a soft ceiling. the auction will test it.',
    nudge30s: 'agree on your top three.',
    nudge90s: 'one minute to bidding. lock your strategy.',
    ceilingLabel: 'soft ceiling',
    keyboardHint: 'focus a card and press M, N, or W to assign a zone.',
  },
  auction: {
    live: 'live now.',
    bidCta: 'bid',
    bidPlaced: 'bid in.',
    won: 'locked in.',
    refundNeverHappens: 'no refunds. once spent, gone.',
    restrategise: 'two minutes. regroup. adjust.',
    nextBidLabel: 'your bid',
    noBidsYet: 'no bids yet. open it up.',
    insufficientCredos: 'not enough credos for that bid.',
    mustBeatHigh: 'must beat the current high.',
  },
  reflection: {
    prompts: [
      'which values did you secure that you didn’t intend to?',
      'which did you miss?',
      'what did this force you to trade off?',
      'what kind of company have you just become?',
    ],
    purpose:
      'write your company’s purpose in one sentence. it must honour three of the values you won — name them explicitly.',
    placeholder: 'we exist to...',
    starter: (v1: string, v2: string, v3: string) =>
      `we exist to ___, by championing ${v1}, ${v2}, and ${v3}.`,
    starterHelp: 'starter — edit to make it yours.',
    useStarter: 'start from this',
    next: 'next',
    submit: 'submit',
    ready: 'your identity card is ready. open it, share it, screenshot it.',
  },
  regather: {
    cta: 'share your identity card.',
    qr: 'scan to keep playing — windedvertigo.com/play',
    download: 'download identity card',
  },
  facilitator: {
    startSession: 'start session',
    nextAct: 'next act',
    extend: '+30 sec',
    jumpConfirm:
      'you’re about to jump acts — this is irreversible for the session feel. continue?',
    continue: 'continue',
    cancel: 'cancel',
    broadcastLabel: 'broadcast a message',
    broadcastSend: 'send',
    startAuction: 'start auction',
    onTheBlock: 'on the block',
    liveSignal: 'live signal',
    tools: 'tools',
    resetBid: 'reset current bid',
    refundCredos: 'refund credos',
    muteTeam: 'mute team',
    deckLabel: 'value deck',
  },
  wall: {
    joinAt: (code: string) => `join at windedvertigo.com/play · code ${code}`,
    waitingLabel: 'waiting for participants',
    betweenActs: 'between acts',
  },
  errors: {
    sessionNotFound: 'session not found. check the code with your facilitator.',
    bidRejected: 'bid rejected.',
  },
} as const;
