/**
 * rhythm-lab Worker entry — wraps OpenNext's emitted worker with
 * @windedvertigo/security for response-header injection.
 *
 * Mirrors apps/depth-chart/worker.ts. See docs/security/cf-headers-wrapper.md
 * for the full pattern + rollout doc.
 */

// @ts-ignore — generated by `npx opennextjs-cloudflare build`, gitignored
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

import {
  wrapWithSecurityHeaders,
  HARBOUR_DEFAULT_CSP,
} from "@windedvertigo/security";

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

// Append a media-src directive so the beat grid can play its silent WAV data:
// URI through an HTMLAudioElement — that promotes the iOS audio session to
// "playback" so the ring/silent switch no longer mutes Web Audio. The shared
// HARBOUR_DEFAULT_CSP has no media-src, so it falls back to default-src 'self'
// which blocks data:. Appended per-app to avoid touching every CF app.
const RHYTHM_LAB_CSP = `${HARBOUR_DEFAULT_CSP}; media-src 'self' data:`;

export default wrapWithSecurityHeaders(openNextHandler, {
  csp: RHYTHM_LAB_CSP,
  skipPaths: [/^\/cdn-cgi\//],
});
