/**
 * raft-house Worker entry — wraps OpenNext's emitted worker with
 * @windedvertigo/security for response-header injection, AND routes the
 * real-time WebSocket subtree to a PartyServer Durable Object.
 *
 * Routing precedence (in `fetch`):
 *   1. PartyServer first: /harbour/raft-house/parties/:namespace/:room/* →
 *      RaftRoom DO. The prefix matches the Next basePath + "parties" so the
 *      direct CF Workers Route (`windedvertigo.com/harbour/raft-house/parties/*`,
 *      defined in wrangler.jsonc) sends WS upgrades straight to this Worker,
 *      bypassing the wv-site proxy. WebSocket upgrades do not reliably traverse
 *      Next.js rewrites; this direct-route + most-specific-match pattern mirrors
 *      apps/harbour/wrangler.jsonc's /api/auth carve-out.
 *   2. Everything else falls through to OpenNext (the Next app), then through
 *      the @windedvertigo/security wrapper for response-header injection.
 *
 * RaftRoom is re-exported below — Wrangler binds DO classes by *exported class
 * name* at deploy time, same rule as DOQueueHandler/DOShardedTagCache/BucketCachePurge.
 * Missing the export = deploy fails with "Durable Object class not found".
 *
 * See docs/security/cf-headers-wrapper.md for the @windedvertigo/security pattern.
 */

import { routePartykitRequest } from "partyserver";

// @ts-ignore — generated by `npx opennextjs-cloudflare build`, gitignored
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

import { wrapWithSecurityHeaders } from "@windedvertigo/security";

import { RaftRoom } from "./party/room";

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge, RaftRoom };

/**
 * raft-house-specific Content-Security-Policy.
 *
 * Mirrors what apps/raft-house/next.config.ts declares in `async headers()`,
 * because OpenNext-on-Cloudflare-Workers does NOT honour Next.js
 * `next.config.ts headers()` — those rules are translated by Vercel's edge
 * at build time, not by the CF Worker. The @windedvertigo/security wrapper
 * is the runtime path for headers on CF; we pass this CSP to it instead of
 * HARBOUR_DEFAULT_CSP because raft-house has app-specific allowances that
 * other CF-routed harbour apps don't:
 *
 *   - https://js.stripe.com           — Stripe.js loader (checkout flow)
 *   - https://api.stripe.com          — Stripe API calls from the client
 *   - https://accounts.google.com     — Google OAuth (sign-in popup + form)
 *   - wss://windedvertigo.com         — PartyServer real-time on apex
 *   - wss://www.windedvertigo.com     — PartyServer real-time on www
 *
 * `'self'` covers same-origin wss:// in modern browsers, but listing the
 * explicit wss: origins is defence-in-depth against older user agents that
 * don't apply 'self' to the ws/wss scheme.
 *
 * The base allowances (windedvertigo.com origins for harbour-nav-widget +
 * feedback-widget; api.notion.com for the CMS-content fetch) match
 * HARBOUR_DEFAULT_CSP from @windedvertigo/security.
 */
const RAFT_HOUSE_CSP: string = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' https://windedvertigo.com https://www.windedvertigo.com https://js.stripe.com",
  "style-src 'self' 'unsafe-inline'",
  "font-src 'self'",
  "img-src 'self' data: https:",
  "connect-src 'self' https://api.notion.com https://windedvertigo.com https://www.windedvertigo.com https://api.stripe.com https://accounts.google.com wss://windedvertigo.com wss://www.windedvertigo.com",
  "frame-src 'self' https://www.youtube.com https://js.stripe.com https://accounts.google.com",
  "frame-ancestors 'none'",
  "worker-src 'self'",
  "base-uri 'self'",
  "form-action 'self' https://accounts.google.com",
].join("; ");

const nextHandler = wrapWithSecurityHeaders(openNextHandler, {
  csp: RAFT_HOUSE_CSP,
  skipPaths: [/^\/cdn-cgi\//],
});

export default {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    const partyResponse = await routePartykitRequest(request, env as Record<string, unknown>, {
      prefix: "harbour/raft-house/parties",
    });
    if (partyResponse) return partyResponse;
    // @ts-ignore — openNextHandler's Env type is structurally compatible
    return nextHandler.fetch(request, env, ctx);
  },
};
