/**
 * raft-house Worker entry — wraps OpenNext's emitted worker with
 * @windedvertigo/security for response-header injection, AND routes the
 * real-time WebSocket subtree to a PartyServer Durable Object.
 *
 * Routing precedence (in `fetch`):
 *   1. PartyServer first: /harbour/raft-house/parties/:namespace/:room/* →
 *      RaftRoom DO. The prefix matches the Next basePath + "parties" so the
 *      direct CF Workers Route (`windedvertigo.com/harbour/raft-house/parties/*`,
 *      defined in wrangler.jsonc) sends WS upgrades straight to this Worker,
 *      bypassing the wv-site proxy. WebSocket upgrades do not reliably traverse
 *      Next.js rewrites; this direct-route + most-specific-match pattern mirrors
 *      apps/harbour/wrangler.jsonc's /api/auth carve-out.
 *   2. Everything else falls through to OpenNext (the Next app), then through
 *      the @windedvertigo/security wrapper for response-header injection.
 *
 * RaftRoom is re-exported below — Wrangler binds DO classes by *exported class
 * name* at deploy time, same rule as DOQueueHandler/DOShardedTagCache/BucketCachePurge.
 * Missing the export = deploy fails with "Durable Object class not found".
 *
 * See docs/security/cf-headers-wrapper.md for the @windedvertigo/security pattern.
 */

import { routePartykitRequest } from "partyserver";

// @ts-ignore — generated by `npx opennextjs-cloudflare build`, gitignored
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

import {
  wrapWithSecurityHeaders,
  HARBOUR_DEFAULT_CSP,
} from "@windedvertigo/security";

import { RaftRoom } from "./party/room";

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge, RaftRoom };

const nextHandler = wrapWithSecurityHeaders(openNextHandler, {
  csp: HARBOUR_DEFAULT_CSP,
  skipPaths: [/^\/cdn-cgi\//],
});

export default {
  async fetch(request: Request, env: unknown, ctx: ExecutionContext): Promise<Response> {
    const partyResponse = await routePartykitRequest(request, env as Record<string, unknown>, {
      prefix: "harbour/raft-house/parties",
    });
    if (partyResponse) return partyResponse;
    // @ts-ignore — openNextHandler's Env type is structurally compatible
    return nextHandler.fetch(request, env, ctx);
  },
};
