/**
 * creaseworks mini canary — worker entry.
 *
 * The mini flavour is built with CW_MINI=1, which bakes basePath
 * /harbour/creaseworks-mini into assets and links, and is routed on the
 * main domain at windedvertigo.com/harbour/creaseworks-mini (zone routes
 * in wrangler.mini.jsonc). This wrapper redirects anything outside the
 * basePath — the bare basePath itself, and "/" on workers.dev — to the
 * /mini welcome page, so both entry URLs land somewhere friendly.
 *
 * Re-exports the OpenNext DO classes verbatim — wrangler drops them
 * otherwise and the deploy fails (see CLAUDE.md, raft-house exception).
 *
 * Mini-canary only: prod creaseworks keeps main = .open-next/worker.js.
 */

// @ts-ignore — generated by `npx opennextjs-cloudflare build`, gitignored
import openNextHandler, {
  // @ts-ignore — see above
  DOQueueHandler,
  // @ts-ignore — see above
  DOShardedTagCache,
  // @ts-ignore — see above
  BucketCachePurge,
} from "./.open-next/worker.js";

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

const BASE = "/harbour/creaseworks-mini";

export default {
  fetch(request: Request, env: unknown, ctx: unknown): Promise<Response> | Response {
    const url = new URL(request.url);
    // bare basePath (with or without trailing slash) or any path outside
    // it (e.g. "/" on workers.dev) → the mini welcome page
    const bare = url.pathname === BASE || url.pathname === `${BASE}/`;
    if (bare || !url.pathname.startsWith(BASE)) {
      return Response.redirect(`${url.origin}${BASE}/mini`, 302);
    }
    return (openNextHandler as { fetch: (r: Request, e: unknown, c: unknown) => Promise<Response> }).fetch(
      request,
      env,
      ctx,
    );
  },
};
