/**
 * creaseworks mini canary — worker entry.
 *
 * The mini flavour is built with CW_MINI=1, which bakes basePath
 * /harbour/creaseworks-mini into assets and links, and is routed on the
 * main domain at windedvertigo.com/harbour/creaseworks-mini (zone routes
 * in wrangler.mini.jsonc). This wrapper redirects anything outside the
 * basePath — the bare basePath itself, and "/" on workers.dev — to the
 * /mini welcome page, so both entry URLs land somewhere friendly.
 *
 * Re-exports the OpenNext DO classes verbatim — wrangler drops them
 * otherwise and the deploy fails (see CLAUDE.md, raft-house exception).
 *
 * Mini-canary only: prod creaseworks keeps main = .open-next/worker.js.
 */

// @ts-expect-error — generated by `npx opennextjs-cloudflare build`, gitignored
import openNextHandler, {
  // @ts-expect-error — see above
  DOQueueHandler,
  // @ts-expect-error — see above
  DOShardedTagCache,
  // @ts-expect-error — see above
  BucketCachePurge,
} from "./.open-next/worker.js";

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

const BASE = "/harbour/creaseworks-mini";

// legacy stage URLs → the "arc" URLs (301). Keys are the old public paths, in
// order so the longest/most-specific segments match first. Sub-paths ride along
// (e.g. /look/classic → /find/classic).
const ARC_301: Array<[RegExp, string]> = [
  [/^\/look(?=\/|$)/, "/find"],
  [/^\/make(?=\/|$)/, "/fold"],
  [/^\/show(?=\/|$)/, "/unfold"],
  [/^\/wow(?=\/|$)/, "/find-again"],
];

export default {
  fetch(request: Request, env: unknown, ctx: unknown): Promise<Response> | Response {
    const url = new URL(request.url);
    // paths outside the basePath (e.g. "/" on workers.dev) → the pilot
    // entry. the bare basePath itself is served directly: the CW_MINI
    // build rewrites "/" to the welcome page, so no redirect and no
    // /mini tail in the URL bar.
    if (!url.pathname.startsWith(BASE)) {
      return Response.redirect(`${url.origin}${BASE}`, 302);
    }
    // 301 legacy /look|/make|/show|/wow (and sub-paths) to the arc URLs
    const rest = url.pathname.slice(BASE.length); // e.g. "/look/classic"
    for (const [re, to] of ARC_301) {
      if (re.test(rest)) {
        const newPath = BASE + rest.replace(re, to);
        return Response.redirect(`${url.origin}${newPath}${url.search}`, 301);
      }
    }
    return (openNextHandler as { fetch: (r: Request, e: unknown, c: unknown) => Promise<Response> }).fetch(
      request,
      env,
      ctx,
    );
  },
};
