/**
 * Creaseworks Worker entry — wraps OpenNext's emitted worker with
 * @windedvertigo/security for response-header injection and dispatches
 * cron triggers to the existing /api/cron/* Next.js routes.
 *
 * Mirrors apps/depth-chart/worker.ts. See docs/security/cf-headers-wrapper.md
 * for the full pattern + rollout doc.
 *
 * Cron dispatch: the wrangler `triggers.crons` block fires the scheduled()
 * handler with `controller.cron` matching the cron string. We map each
 * string to its Next.js cron-handler path and invoke it via the
 * WORKER_SELF_REFERENCE service binding so the request flows through
 * the OpenNext-emitted worker the same way an external HTTP request would.
 */

// @ts-ignore — generated by `npx opennextjs-cloudflare build`, gitignored
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

import { wrapWithSecurityHeaders } from "@windedvertigo/security";

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

/**
 * Creaseworks CSP. Mirrors the policy defined in next.config.ts
 * `headers()` exactly — that policy is honoured on Vercel via platform
 * header rules, but OpenNext-on-CF-Workers does not, so we re-declare
 * it here for the wrapper to inject. Adds frame-ancestors 'none' as
 * defence-in-depth alongside X-Frame-Options: DENY.
 *
 * Keep this in sync with apps/creaseworks/next.config.ts headers().
 */
const CREASEWORKS_DEFAULT_CSP: string = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' https://js.stripe.com",
  "style-src 'self' 'unsafe-inline'",
  "font-src 'self'",
  "img-src 'self' data: https:",
  "connect-src 'self' https://api.stripe.com https://vitals.vercel-insights.com https://api.notion.com",
  "frame-src https://js.stripe.com",
  "frame-ancestors 'none'",
  "worker-src 'self'",
  "base-uri 'self'",
  "form-action 'self'",
].join("; ");

const wrapped = wrapWithSecurityHeaders(openNextHandler, {
  csp: CREASEWORKS_DEFAULT_CSP,
  skipPaths: [/^\/cdn-cgi\//],
});

/**
 * Map cron string -> Next.js API route. Keep in sync with
 * `triggers.crons` in wrangler.jsonc and the schedules in vercel.json.
 */
const CRON_ROUTES: Record<string, string> = {
  "0 6 * * *": "/api/cron/sync-notion",
  "0 9 * * 1": "/api/cron/send-digests",
  "0 8 * * *": "/api/cron/send-nudges",
};

type Env = {
  WORKER_SELF_REFERENCE: { fetch: (req: Request) => Promise<Response> };
  CRON_SECRET?: string;
};

export default {
  ...wrapped,
  fetch: wrapped.fetch,
  /**
   * Cloudflare cron-trigger entry. Dispatches each cron's matching
   * /api/cron/* route via the self-reference service binding so the
   * existing Next.js handler runs unchanged.
   *
   * Expects CRON_SECRET set as a wrangler secret; the handlers use
   * Bearer-auth on the Authorization header for direct invocation.
   */
  async scheduled(
    controller: { cron: string; scheduledTime: number; noRetry(): void },
    env: Env,
    ctx: { waitUntil(p: Promise<unknown>): void },
  ): Promise<void> {
    const path = CRON_ROUTES[controller.cron];
    if (!path) {
      console.error(`scheduled: no route for cron ${controller.cron}`);
      return;
    }

    const url = `https://wv-harbour-creaseworks${path}`;
    const headers: Record<string, string> = {};
    if (env.CRON_SECRET) {
      headers["Authorization"] = `Bearer ${env.CRON_SECRET}`;
    }

    ctx.waitUntil(
      env.WORKER_SELF_REFERENCE.fetch(new Request(url, { headers }))
        .then((res) => {
          if (!res.ok) {
            console.error(
              `scheduled: ${path} returned ${res.status} for cron ${controller.cron}`,
            );
          }
        })
        .catch((err) => {
          console.error(`scheduled: ${path} failed:`, err);
        }),
    );
  },
};
