/**
 * Vertigo-vault Worker entry — wraps OpenNext's emitted worker with
 * @windedvertigo/security for response-header injection, and adds a
 * scheduled() handler for the daily Notion-sync cron (formerly a Vercel
 * cron job at /api/cron/sync).
 *
 * Mirrors apps/depth-chart/worker.ts. See docs/security/cf-headers-wrapper.md
 * for the full pattern + rollout doc.
 */

// @ts-ignore — generated by `npx opennextjs-cloudflare build`, gitignored
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

import { wrapWithSecurityHeaders } from "@windedvertigo/security";

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

// Vault-specific CSP fallback. Acts as a safety net for response paths
// that bypass middleware.ts (which generates a per-request nonce-based
// CSP with 'strict-dynamic' and sets it on the response — the security
// wrapper preserves an inner CSP, so page responses keep nonce-strength).
//
// This fallback lacks per-request nonces and 'strict-dynamic', so it's
// a weaker policy by design — it only applies if middleware didn't run
// (e.g. asset responses, edge errors). Stripe + Vercel insights URLs
// stay in connect-src/frame-src to support runtime checkout flows on
// any non-middleware path that still renders Stripe assets.
const VAULT_CSP_FALLBACK = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' https://js.stripe.com",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data: https:",
  "connect-src 'self' https://api.stripe.com",
  "frame-src https://js.stripe.com https://hooks.stripe.com",
  "frame-ancestors 'none'",
  "worker-src 'self'",
  "base-uri 'self'",
  "form-action 'self'",
].join("; ");

const securedHandler = wrapWithSecurityHeaders(openNextHandler, {
  csp: VAULT_CSP_FALLBACK,
  skipPaths: [/^\/cdn-cgi\//],
});

// Compose the scheduled() handler onto the wrapped fetch handler.
// The CF Workers runtime invokes scheduled() at each cron trigger
// (wrangler.jsonc → triggers.crons). We call the cron endpoint
// internally via the worker's own fetch handler so the existing
// CRON_SECRET-protected route stays the single source of truth for
// sync logic — same pattern is reusable from a manual curl.
export default {
  ...securedHandler,
  async scheduled(
    _controller: { cron: string; scheduledTime: number },
    env: { CRON_SECRET?: string },
    ctx: { waitUntil(p: Promise<unknown>): void },
  ): Promise<void> {
    const cronSecret = env.CRON_SECRET;
    if (!cronSecret) {
      console.error("[scheduled] CRON_SECRET not set — skipping vault sync");
      return;
    }

    // basePath is /harbour/vertigo-vault — the cron route handler lives
    // at /api/cron/sync under that. Hostname is arbitrary for an internal
    // fetch (the Worker self-handles); use the workers.dev URL so the
    // request looks well-formed.
    const url =
      "https://wv-vault.windedvertigo.workers.dev" +
      "/harbour/vertigo-vault/api/cron/sync";

    const work = (async () => {
      try {
        const res = await securedHandler.fetch(
          new Request(url, {
            method: "POST",
            headers: { authorization: `Bearer ${cronSecret}` },
          }),
          env as never,
          ctx as never,
        );
        const body = await res.text();
        if (!res.ok) {
          console.error(
            `[scheduled] vault sync returned ${res.status}: ${body.slice(0, 500)}`,
          );
        } else {
          console.log(`[scheduled] vault sync ok: ${body.slice(0, 500)}`);
        }
      } catch (err) {
        console.error("[scheduled] vault sync threw:", err);
      }
    })();

    ctx.waitUntil(work);
  },
};
