/**
 * Vertigo-vault Worker entry — wraps OpenNext's emitted worker with
 * @windedvertigo/security for response-header injection, and adds a
 * scheduled() handler for the daily Notion-sync cron.
 *
 * Mirrors apps/depth-chart/worker.ts and apps/harbour/worker.ts.
 * See docs/security/cf-headers-wrapper.md for the wrapping pattern.
 *
 * GATE A.1 DECISION (Stripe DLQ store): Cloudflare KV.
 * Vault has no pre-existing Upstash/Redis dependency, so we use the
 * Worker runtime's native KV binding (STRIPE_DLQ in wrangler.jsonc) to
 * minimise the number of external services to provision at cutover.
 *
 * STAGED ONLY — not deployed. Production vault remains on Vercel until
 * the cutover plan is greenlit post-launch.
 */

// @ts-ignore — generated by `npx opennextjs-cloudflare build`, gitignored
import openNextHandler, {
  // @ts-ignore
  DOQueueHandler,
  // @ts-ignore
  DOShardedTagCache,
  // @ts-ignore
  BucketCachePurge,
} from "./.open-next/worker.js";

import {
  wrapWithSecurityHeaders,
  type MinimalScheduledController,
  type MinimalExecutionContext,
} from "@windedvertigo/security";

// Re-export Durable Object classes verbatim so wrangler's bundler keeps
// them in the deployed worker. Without these, deploy fails the moment
// OpenNext tries to instantiate the queue / sharded-tag-cache /
// bucket-cache-purge DOs declared in wrangler.jsonc bindings.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge };

/**
 * Vault-specific Content-Security-Policy.
 *
 * Mirrors what apps/vertigo-vault/middleware.ts emits today on Vercel,
 * MINUS the `'nonce-...'` and `'strict-dynamic'` Level-3 directives
 * (the wrapper sets a static CSP per response — per-request nonce
 * generation requires a richer wrapping API and is tracked as a future
 * iteration in docs/security/cf-headers-wrapper.md).
 *
 * Differences from middleware.ts:
 *   - script-src drops 'nonce-...' and 'strict-dynamic'; falls back to
 *     'unsafe-inline' for Next.js hydration scripts. Acceptable
 *     defence-in-depth on Workers; revisit when the wrapper supports
 *     nonces.
 *   - Adds Stripe + Vercel-vitals connect-src/frame-src origins (carry
 *     forward from middleware.ts).
 *   - Adds frame-ancestors 'none' for clickjacking defence.
 */
const VAULT_DEFAULT_CSP: string = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline' https://js.stripe.com",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com",
  "img-src 'self' data: https:",
  "connect-src 'self' https://vitals.vercel-insights.com https://api.stripe.com https://api.notion.com",
  "frame-src https://js.stripe.com https://hooks.stripe.com",
  "frame-ancestors 'none'",
  "worker-src 'self'",
  "base-uri 'self'",
  "form-action 'self'",
].join("; ");

const wrappedHandler = wrapWithSecurityHeaders(openNextHandler, {
  csp: VAULT_DEFAULT_CSP,
  skipPaths: [/^\/cdn-cgi\//],
});

/**
 * Scheduled handler — fires once daily at 06:00 UTC per wrangler.jsonc
 * `triggers.crons`. Calls the existing /api/cron/sync route handler
 * internally (so business logic stays in the Next.js app, not in this
 * worker shim) using the worker's own self-binding.
 *
 * On Vercel, this same route is triggered by vercel.json `crons`. Both
 * platforms pass the CRON_SECRET as a Bearer token; the route's bearer
 * check is unchanged.
 */
type Env = {
  WORKER_SELF_REFERENCE: { fetch: (req: Request) => Promise<Response> };
  CRON_SECRET?: string;
  // KV binding for Stripe DLQ — referenced by lib/webhook-dlq.ts at
  // request time via the runtime's getCloudflareContext().env.STRIPE_DLQ.
  STRIPE_DLQ: KVNamespace;
};

interface KVNamespace {
  get(key: string, options?: { type?: "text" | "json" }): Promise<string | null>;
  put(
    key: string,
    value: string,
    options?: { expirationTtl?: number },
  ): Promise<void>;
  delete(key: string): Promise<void>;
}

export const scheduled = async (
  controller: MinimalScheduledController,
  env: Env,
  ctx: MinimalExecutionContext,
): Promise<void> => {
  const url =
    "https://wv-harbour-vertigo-vault.windedvertigo.com/harbour/vertigo-vault/api/cron/sync";
  const cronSecret = env.CRON_SECRET ?? "";
  const work = env.WORKER_SELF_REFERENCE.fetch(
    new Request(url, {
      method: "POST",
      headers: { authorization: `Bearer ${cronSecret}` },
    }),
  ).then((res) => {
    if (!res.ok) {
      console.error(
        `[scheduled] /api/cron/sync returned ${res.status} (cron=${controller.cron})`,
      );
    }
  });
  ctx.waitUntil(work);
};

export default wrappedHandler;
